#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1635162774                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : nl                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://petervandoorn.com                 # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :  assets/icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Find, Photograph, Score!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Peter van Doorn                               
your_link                                 : https://petervandoorn.com                     
your_city                                 : Amsterdam                                
email_address                             : photoscavenger@petervandoorn.com
facebook_username                         :                                           
instagram_username                        : two.trick.pony_
twitter_username                          : 
github_username                           : two-trick-pony-NL
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Find, Photograph, Score!
    description                           : Win from friends and family by taking photos of objects. You score points for every item found in the picture and lose points if you have to refresh.
    fontawesome_icon_name                 : play-circle
  
  - title                                 : Using AI to detect objects
    description                           : PhotoScavenger uses the latest AI techniques to detect objects in the pictures you snap 
    fontawesome_icon_name                 : magic

  - title                                 :  Objectives get harder as you go
    description                           :  PhotoScavenger might look like a simple game, and it is. But beware, the more points you score the harder the objectives get!
    fontawesome_icon_name                 :  binoculars
    
  - title                                 : All you need is your iPhone
    description                           : All you need to play PhotoScavenger is your iPhone
    fontawesome_icon_name                 : mobile

  - title                                 :  Privacy friendly
    description                           :  No data is collected, no ads and the photos you take are removed after processing
    fontawesome_icon_name                 :  binary-circle-check

  - title                                 :  Free to play
    description                           :  Because PhotoScavenger is a fun side-project of mine, there are 0 ads and the app costst $0
    fontawesome_icon_name                 :  money-bill




  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#363b3d"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
